# Which CAN message contains the highest number of signals?

PREFIX dbc:  <http://example.org/dbc#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?message (COUNT(DISTINCT ?signal) AS ?signalCount)
WHERE {
    ?message a dbc:Message .
    ?signal dbc:isPartOf ?message .

}
GROUP BY ?message
ORDER BY DESC(?signalCount)
LIMIT 1



