# Which CAN messages are observable on the bus?

PREFIX dbc:  <http://example.org/dbc#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

SELECT ?message
WHERE {
    ?message a dbc:Message ;	
}

