# Which unit is assigned to the signal log of the fresh water tank?

PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX dbc:  <http://example.org/dbc#>
PREFIX ex: <http://example.org/individuals#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT DISTINCT ?unit 
WHERE {
    ?signallog sosa:observedProperty ex:FreshwaterTank14 .
	ex:FreshwaterTank14 qudt:hasUnit ?unit .

}


