# Which message logs were most recently recorded on can2 bus?

PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX dbc:  <http://example.org/dbc#>
PREFIX ex:   <http://example.org/individuals#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>

SELECT ?messagelog ?data
WHERE {
  ?messagelog a dbc:MessageLog ;
              dbc:busName ex:can2 ;
              sosa:hasSimpleResult ?data ;
              sosa:resultTime ?timestamp .
}
ORDER BY DESC(?timestamp)
LIMIT 300



